version: "3.7"
services:
  native:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: builder
    working_dir: /usr/local
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    tty: true
    volumes:
    - ./src:/usr/local/src
    - ./build.sh:/usr/local/build.sh
